### ISSUE TITLE
warning in LOGfile

### ISSUE THREAD

**Issue by simpixo** [frankjoke/ioBroker.radar#15]
Ich erhalte seit neustem folgende warning

Scan devices returned error: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null at pSeriesP (/opt/iobroker/node_modules/iobroker.radar/radar.js:56:20) at Promise.all.pExec.then.

Ist das ein Fehler im Adapter oder bei mir im System

**Comment by frankjoke** [comment]
Hi Simpixio!

Der Fehler entsteht anscheinen weil irgend eine Frunktion keine Daten zurückgibt (null z.B) anstatt ein leeres Objekt oder Array.
Welche Version von Radar und Node verwendest du? 
Kannst im Log schauen ob auch mehr angezeigt wird (also die aufrufende Codezeile)?
Hast irgendwas geändert (updates, Einstellungen,  system oder node-Version) bevor der Fehler anfing aufzutreten?

Ich teste auf 3 Minux und einem Windows-System und hatte es noch nicht.

**Comment by simpixo** [comment]
Hallo

also, der Fehler taucht immer wieder auf. In regelmässigen Abständen

Radar Version: 1.1.3
Node: v6.11.5

ich habe den Adapter auf einem neuen Raspberry installiert. Dieser ist als Multihost konfiguriert. Alle benötigten Linux Pakete sind installiert.


das ist die komplette Meldung:


radar.0 | 2017-11-07 21:23:34.252 | debug | Del Object: iPhone-XXX.count
-- | -- | -- | --
radar.0 | 2017-11-07 21:23:34.228 | debug | Del State err: 'Not exists'
radar.0 | 2017-11-07 21:23:31.093 | warn | Scan devices returned error: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null at pSeriesP (/opt/iobroker/node_modules/iobroker.radar/radar.js:56:20) at Promise.all.pExec.then.
radar.0 | 2017-11-07 21:23:30.796 | debug | l2ping for iPhone-XXX err: "Error: Command failed: l2ping -c1 xx:xx:xx:xx:xx:xx Can't connect: Operation already in progress "
radar.0 | 2017-11-07 21:23:30.717 | debug | Error: Command failed: l2ping -c1 xx:xx:xx:xx:xx:xx Can't connect: Operation already in progress
radar.0 | 2017-11-07 21:23:28.928 | debug | Noble= Noble { state: 'poweredOn', address: 'b8:27:eb:09:a2:19', _bindings: NobleBindings { _state: 'poweredOn', _addresses: {}, _addresseTypes: {}, _connectable: {},
radar.0 | 2017-11-07 21:23:28.928 | debug | Would now start scan for devices! Would also scan for printer ink now!

**Comment by neorulez** [comment]
Hi Frank,

I've got the very same problem:

radar.0 | 2018-02-26 17:05:03.865 | warn | Scan devices returned error: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null at pSeriesP (/opt/iobroker/node_modules/iobroker.radar/radar.js:56:20) at Promise.all.pExec.then
-- | -- | -- | --

Additionally, I can't use radar on my Raspberry Pi 3 because from time to time the whole system hangs and isn't reachable in the network.

Any update or ideas?

**Comment by frankjoke** [comment]
Can you test new test version from git v1.2.0?
