### ISSUE TITLE
Massive Broadcasts durch Radar

### ISSUE THREAD

**Issue by MarkSau** [frankjoke/ioBroker.radar#16]
Hi...
Ich hatte massive Ausfälle im WLAN, welche, nach eingehender Untersuchung, durch den Radar Addon erzeugt werden. Dieser schickt massiv Broadcasts ins Netz, wohl um zu prüfen welche Geräte im Netz existieren. Da ich letzte Woche auf ein erweiteretes Class C Netz 192.168.0.0/23 gewechselt bin, werden jetzt wohl 512 Broadcasts verschickt, was dann zur Folge hat, das z.B. mein RPi streckenweise nicht erreichbar ist und meine Hausautomation ebenfalls dadurch massiv Probleme hat...streckenweise Pingzeiten von 3000-4000ms
Kann man diese Broadcasts bzw. den Scan evtl. abschalten? Wenn ich Radar stoppe sind die Pings normal mit 6-100ms

**Comment by frankjoke** [comment]
Hallo MarkSau! ich weiss nicht welches equipment du hast für ioBroker aber radar unter linux versucht mittels arp-scan einen Broadcast abzusenden, aber dies sollte ja kein Problem darstellen.

Der Adapter verwendet auf fping wenn da, und wenn nicht da nur ping. 

Du kannst fping und arp-scan abschalten indem du die Kommandos umbenennst.

Suche sie mit
which arp-scan 
oder
which fping

dann mit sudo umbenennen.

p.s.: Wenn du dadurch Probleme hast würde ich den Router tauschen! Die Befehle versauen normal kein internet und wenn du lange Zugriffszeiten hast dann hast normal Probleme mit ipv4/ipv6 DNS und nicht durch Radar.

**Comment by MarkSau** [comment]
Danke für die Antwort...ich habe eine Fritzbox 7490 mit zwei 1750 Repeater im Einsatz.
Ich habe mir den Wireshark Trace mal etwas genauer angeschaut. Ein mal Arpscan alle eingestellten z.b. 60sec wäre ja ok, aber warum wird der Scan direkt div. male hintereinander gemacht? Ich sehe das stellenweise über 10mal der gleiche Broadcast verschickt wird. Kann ich das irgendwo einschränken? Einmal sollte ja reichen.

**Comment by frankjoke** [comment]
Ok, hab auch eine Fritzbox und keine Probleme, auch wenn testweise auf 3 Geräten radar läüft und abfragt.

Die Abfragefrequenz kann man im radar-admin einstellen, bei mir ist sie auf 60, d.h. alle 60 Sekunden, so wie bei dir.
Die scans werden nur wiederholt wenn sie Fehler bringen, was sie aber nicht tun sollte. 

mach mal
sudo arp-scan -lgq
das macht radar auch.

**Comment by MarkSau** [comment]
Hi,

ich habe nun mal wieder Zeit gehabt, mich weiter mit dem Thema zu beschäftigen.
Es ist definitiv so, das wenn ich Radar aktiviere, die Pingzeiten drastisch in die Höhe gehen.
In der angehängten Grafik sieht man in der linken Hälfte inkl. Radar, rechts ohne...
![ping_history_192 168 0 12_2018-04-12_17h19](https://user-images.githubusercontent.com/22911084/38687161-4a02f13c-3e76-11e8-8984-95884a282d3e.png)
Angepingt habe ich einen RPi3, der via WLAN verbunden ist.
Der Weg sieht in etwa so aus:
RPI3/WLAN---AVMRepater1750---Fritzbox/WLAN ----Netgear Switch----Netgear Switch ---PC

Wenn ich ein sudo arp-scan -lgq von dem IOBroker PI mache, der in der Mitte des oben genannten Wegs verbaut ist, sehe ich die massiven Pingzeiten nicht, wohl aber eine Erhöhung.auf max. 200ms...
Es sieht so aus, als ob Radar mehrfach hintereinander einen arp-scan ausführt, was dann natürlich zu einer hohen Broadcast Last führt und das WLAN etwas zu sehr strapaziert

PS: Der PC war auch schon direkt an der FB...keine Änderung

**Comment by MarkSau** [comment]
Habe gerade mal Wireshark laufen lassen. Diesen nach ARP gefiltert. Wenn Radar startet, sehe ich 7x einen Arp request mit jeweils 255 Broadcasts...das macht also in sehr kurzer Zeit 1785 Stück... Das sollte doch so nicht sein? oder? 
Ich werden jetzt mal die 7 Devices auf 1 oder 2 reduzieren und Wireshark nochmal laufen lassen...

**Comment by MarkSau** [comment]
Könntest du den Scan evtl auch so gestalten?

**Comment by MarkSau** [comment]
Habe in dem radar.js die Zeile         doMac ? pExec('arp-scan -lgq --retry=7')    gefunden...Daher also die 7fache Wiederholung, die ja auch im Trtace zu sehen sind.  Habe es mal auf          doMac ? pExec('arp-scan -lgq --retry=1')  geändert....nun bleibt mein Netz ruhig......ich teste weiter...

**Comment by frankjoke** [comment]
Die Anzahl der retries ist in der jetzigen Version auf Git konfigurierbar!
