### ISSUE TITLE
no arp-scan available

### ISSUE THREAD

**Issue by Michael-Sauer** [frankjoke/ioBroker.radar#21]
Hallo bekomme folgende Warnung:

MAC addresses 'A4:6C:F1:00:BE:A2' will not be scanned because no arp-scan is available!

Arp-scan ist installiert. Adapter ist in einer vorherigen ioBroker Installation schon einmal gelaufen.
Was kann ich machen?

**Comment by frankjoke** [comment]
Hi Michael!

Versuch mal mit root/sudo 
`arp-scan -lgq --retry=7`

Der Adapter ruft arp-scan auf und wenn er einen Fehler bekommt meldet er mit obiger Warnung.
Der Fehler kann durch arp-scan oder das Betriebssystem (wenn der Adapter nicht als root läuft) kommen.

LG
Frank

**Comment by Michael-Sauer** [comment]
Danke für die Info. 

Wenn ich es ohne Root/sudo aufrufe kommt ein "Speicherzugriffsfehler".

Wenn ich es mit `sudo arp-scan -lgq --retry=7` aufrufe kommt die 

Fehlermeldung:
`WARNING: Could not obtain IP address for interface eth0. Using 0.0.0.0 for
the source address, which is probably not what you want.
Either configure eth0 with an IP address, or manually specify the address
with the --arpspa option.
Interface: eth0, datalink type: EN10MB (Ethernet)
ERROR: Could not obtain interface IP address and netmask
ERROR: pcap_lookupnet: eth0: no IPv4 address assigned`

Habe es dann mal mit `sudo arp-scan -lgq -I br0 --retry=7` probiert wo er 
mir alle Netzwerkadressen auflistet. 

Was und wo muss ich ändern das es im ioBroker läuft?

Danke für die Unterstützung.

**Comment by frankjoke** [comment]
Ok, I'm not a linux/network specialist but it seems you have other than direct connected network running.

Just try `ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether a2:ca:83:42:ff:a2 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether a2:ca:83:42:ff:a3 brd ff:ff:ff:ff:ff:ff
`

As you see on my orange-pi I am connected to eth0 (it's UP) and it works 
You need to check/change your network setting until arp-scan works without the -I option. This shoulöd be the case if you enable only the right network and disable the rest (like I did with wlan).

BR
Frank

**Comment by Michael-Sauer** [comment]
So sieht es bei mir aus.
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00`

`2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UP mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:16:7a:e3 brd ff:ff:ff:ff:ff:ff`

`3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:43:2f:b6 brd ff:ff:ff:ff:ff:ff`

`4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:16:7a:e3 brd ff:ff:ff:ff:ff:ff`

`6: vethpivccu@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP mode DEFAULT group default qlen 1000
    link/ether fe:58:40:d2:c7:3a brd ff:ff:ff:ff:ff:ff link-netnsid 0
`

Auf meinem Raspberry läuft gleichzeitig pivccu.

**Comment by frankjoke** [comment]
Anscheinend hat dein Rechner durch die CCU eine bridge.
Möglicherweise kannst du die Netzwerk-konfig umschreiben damit bro nummer 2 wird und eth0 nummer 4, vielleicht geht's dann aber ich bin leider kein Netzwerk-Spezialist auf Linux!

**Comment by ue30er** [comment]
Gleiches Problem auch bei mir.
Der Raspi arbeitet gleichzeitig als CCU und hat daher die Bridge.

Da bei dir die Abfrage mit dem einfügen von " -I br0 " funktioniert hat... (bei mir auch, nur mit ' -I yahmbr0 ' habe ich kurzerhand die Datei 'radar.js' im Adapter-Verzeichnis an allen Stellen wo "arp-scan" durchgeführt wird mit dem obigen ergänzt und siehe da... funktioniert...

Als Work-around vielleicht erstmal machbar.

Dem Ersteller des Adapters: Vielleicht kann man sowas "als Extra" im Konfig-Menü unterbringen? Einfaches Feld wo man das eintragen kann... wenn ausgefüllt wird im Script halt '-I WERT' hinzugefügt in allen arp-scan-exec's; wenn leer, dann nicht.

**Comment by Michael-Sauer** [comment]
Hat funktioniert.

Danke für die Hilfe.

**Comment by frankjoke** [comment]
Ok, tipp aufgenommen und und für nächste Version im Hinterkopft!

**Comment by ltsalvatore** [comment]
hallo zusammen, 
kurze frage.. 

ich bin von raspberry pi auf nuc mit proxmox und debian umgestiegen und bin gerade dabei alle adapter auf dem neuen iobroker server zu installieren. 

jetzt ist mir aufgefallen, dass der radar adapter garnicht mehr so sauber funktioniert.. 
sprich, der adapter ist zwar online und aktiv aber die werte in den objekten sind alles falsch.
sowohl auf dem alten als auch auf dem neuen system.


habe versucht das ganze hier etwas zu verstehen und umzusetzen.. aber ich blick da noch nicht so ganz durch.. 

meine settings im radar adapter sehen aktuell so aus: 
![2019-01-21 21_56_08-instances - iobroker](https://user-images.githubusercontent.com/45215717/51498615-73cca680-1dc7-11e9-84a0-b0698ac4d344.jpg)


muss ich evtl. noch was in der shell machen?

**Comment by frankjoke** [comment]
Hast schon die neue 1.2.0-Testversion von git probiert? Einfach mit dem admin über git laden.
Lies dir auch die geänderte Beschreibung auf Git durch, es könnte sein dass du etwas einstellen musst.

Iobroker hat einige wichtige Duinge geändert die leider Adapter besonders betreffen welche root-Rechte brauchen. Man muss dann den iobroker-user sudo fähig machen.

wenn's noch immer nicht geht dann bitte den log welches der Adapter nach dem Start schreibt mal posten.

**Comment by jerzimeik** [comment]
Ich habe ein ähnliches Problem. Bei mir zeigt ip link sho aber folgendens

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
40: eth0@if41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 22:bb:25:24:62:84 brd ff:ff:ff:ff:ff:ff link-netnsid 0

Was kann ich machen?

**Comment by frankjoke** [comment]
Ich sehe keine ipv4 Netzwerke mit ip-adressen! Was sagt ifconfig?

**Comment by frankjoke** [comment]
Habe vergessen, was sagt `sudo arp-scan -lgq` oder für jerzimeik `sudo arp-scan -lgq --interface=eth0`? Funkt das?

**Comment by jerzimeik** [comment]
ifconfig sagt:

`root@iobroker-new:/#`

```
 ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.178.22  netmask 255.255.255.0  broadcast 192.168.178.255
        inet6 fe80::20bb:25ff:fe24:6284  prefixlen 64  scopeid 0x20<link>
        ether 22:bb:25:24:62:84  txqueuelen 1000  (Ethernet)
        RX packets 5309974  bytes 1318230675 (1.2 GiB)
        RX errors 0  dropped 420  overruns 0  frame 0
        TX packets 7536244  bytes 1940382462 (1.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 31987594  bytes 4939395948 (4.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 31987594  bytes 4939395948 (4.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`
```

**Comment by jerzimeik** [comment]
arp-scan macht eigentlich alles:

`root@iobroker-new:/# sudo arp-scan -lgq          
Interface: eth0, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)
192.168.178.1   7c:ff:4d:74:8a:22
192.168.178.14  f4:f2:6d:a4:f8:a6
192.168.178.19  10:7b:ef:bc:53:49
192.168.178.20  00:17:88:6e:d9:49
192.168.178.32  b8:27:eb:d9:2b:a8
192.168.178.31  34:ea:34:58:94:ca
192.168.178.44  b8:27:eb:99:80:6f
192.168.178.60  60:01:94:8c:89:7d
192.168.178.15  28:c6:8e:ad:7e:86
192.168.178.76  cc:9e:a2:f1:7e:1e
192.168.178.78  a0:02:dc:b1:b0:bc
192.168.178.79  c8:63:f1:b8:3c:5d
192.168.178.83  80:7d:3a:32:2a:f1
192.168.178.82  60:01:94:74:00:c9
192.168.178.36  78:11:dc:b2:70:91
192.168.178.90  86:1b:56:91:c9:1d
192.168.178.93  00:1a:22:0e:b8:ac
192.168.178.95  06:09:11:5d:bc:f7
192.168.178.50  60:01:94:ad:d0:3a
192.168.178.96  d2:b5:68:1a:d4:5e
192.168.178.97  96:be:76:a7:51:35
192.168.178.98  b6:7f:73:a5:2f:cc
192.168.178.99  00:01:80:76:8a:a8
192.168.178.103 74:c2:46:b3:5a:b2
192.168.178.104 74:5e:1c:13:5d:43
192.168.178.130 00:25:22:db:ee:62
192.168.178.70  84:20:96:22:90:1f
192.168.178.150 d4:85:64:2b:75:cf
192.168.178.75  5c:cf:7f:57:78:70
192.168.178.86  84:f3:eb:9f:60:da
192.168.178.87  84:f3:eb:32:b8:24
192.168.178.111 c0:25:06:02:df:ee
192.168.178.101 50:f5:da:50:8e:09
192.168.178.202 7c:ff:4d:74:8a:22
192.168.178.23  02:0f:b5:6b:68:81
192.168.178.26  02:0f:b5:fd:10:8f
192.168.178.84  02:0f:b5:e8:c2:36`

**Comment by jerzimeik** [comment]
Im iobroker sieht es dann aber so aus:
![radar](https://user-images.githubusercontent.com/48790822/54808689-48f4b680-4c81-11e9-93ba-a061d7427fff.png)

**Comment by frankjoke** [comment]
Dein Netzwerk schaut normal aus und arp-scan ist auch OK.
Hast du die install-Befehle (schau auf readme install Teil) VOR der Installation ausgeführt? Wenn nicht lösch den Adapter und führe die Befehle aus und installiere ihn dann wieder.

Wenn du ihn startest dann schalte vorher den debug-mode ein und checke alles, es sollten dann eigentlich keine Warnings oder errors kommen.

Wenn doch dann zeig mir den vom Start mit debug.

**Comment by frankjoke** [comment]
Ach übrigens, hab vergessen dass du eigentlich radar2 verwenden solltest! Auch hier muss was vor der Installation gemacht werden, aber ich mache Fehlerkorrekturen nur noch für radar2!

**Comment by jerzimeik** [comment]
Neuer Versuch mit radar2 und streng nach Anleitung ;-)

debug-mode ist an.

Folgende Fehler kommen dann:
![radar2](https://user-images.githubusercontent.com/48790822/54865468-5c2d8200-4d66-11e9-9fe4-3ab4369ee375.png)

Etwas später dann:

![radar2_2](https://user-images.githubusercontent.com/48790822/54865474-5e8fdc00-4d66-11e9-9da8-753a14e3d270.png)

**Comment by frankjoke** [comment]
Jerzimeik, wenn das im Debug-mode ist und die einzige Meldung starting version und radar2 initialization... ist dann stürzt node ab wenn er sich mit den iobroker-js-controller verbinden will.

Es sind SIGSEGV und SIGABRT, also Signale die ich nicht selbst im Adapter erzeuge sonder welche die das Betriebssystem oder js-controller erzeugt.

Andere Kollegen hatten das wenn die npm-Installation fehler gemacht hat und die Treiber nicht richtig kompiliert hat. Vor allem am Rock64 war das der Fall da das Betriebssystem dort die falsche Python-Version installiert hat.

Sonst kann ich dazu nichts sagen aber du kannst mal den Adapter in admin disablen und auf der Kommandozeile folgendes probieren:
`
sudo -u iobroker node /opt/iobroker/node_modules/iobroker.radar2/radar2.js --force --logs --nolazy
`
Dann sollte der gesamte startup mit log und gesamter Fehlermeldung angezeigt werden...

**Comment by frankjoke** [comment]
Übrigens, das ist was ein ordentlich installierter Adapter beim Start meldet (die ersten Zeilen):
`
starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.radar2, node: v8.15.1

radar2 initialization started...

radar2 starting main...

found '@abandonware/noble'

found 'node-bluetooth'

radar2 set to flag items away if they are not seen for 3 minutes

Debug mode set by adapter config ('!' as last letter in removeEnd)!

use known BT list: [ ... ]
`

zwischen initialization started ... und
starting main
versucht der Adapter sich bei ioBroker anzumelden und wenn das passiert ist started er main, also das wirkliche Hauptprogramm, des Adapters welches die Geräte aus der Konfiguration liest und dann das scanning startet.
