### ISSUE TITLE
Scan triggern

### ISSUE THREAD

**Issue by jaffio** [frankjoke/ioBroker.radar#22]
also ich suche jetzt schon seid langem nach einer Lösung. Gibt es wirklich garkeine Möglichkeit den Scan von Geräten von aussen zu starten? Kann ich den nur zeitlich beeinflussen? Oder übersehe ich da etwas?

**Comment by frankjoke** [comment]
Der scan läuft beim Adapter-Start oder nach der scan-time, sonst kann man ihn nicht starten.
Auf manchen Rechnern dauert ein Scan bis zu 20 Sekunden was bedeutet dass bei einem externen Start gerade ein scan laufen kännte.

Ich würde den systeminfo oder javascript Adapter verwenden um etwas abzufragen was schneller gehen muss!

**Comment by frankjoke** [comment]
Hab mir das nochmal angeschaut aber es ist nicht lösbar da einige Programme nicht gleichzeitig laufen können, wird gerade ein Scan gemacht kann kein anderer gestartet werden!
Ich habe die minimum-Zeit zwischen scans auf 15 Sekunden heruntergesetzt und für arp-scan das retry konfigurierbar gemacht damit man den Adapter in kürzeren Intervallen scannen lassen kann.
