### ISSUE TITLE
Scan time.

### ISSUE THREAD

**Issue by anrada73** [frankjoke/ioBroker.radar#23]
Hello, how do I change the scan time to 1 second?

**Comment by frankjoke** [comment]
There is no way to reduc scan time to 1s because several parts of the scan take much more than a second.

**Comment by anrada73** [comment]
well, can there be an opportunity to do 3, 5, 10 seconds?

**Comment by anrada73** [comment]
BLE has a small radius of action and if it is necessary to turn off the alarm, then at 30 seconds the system will not be able to determine BLE. Alarm is triggered

**Comment by anrada73** [comment]
https://hausautomatisierung-koch.de/2017/01/07/anwesenheitserkennung-bluetooth-beacon/

**Comment by frankjoke** [comment]
The new test version V1.2 on git can reduce scan times to 15 seconds.
