### ISSUE TITLE
add device not possible

### ISSUE THREAD

**Issue by speedymk1** [frankjoke/ioBroker.radar#25]
Hi,

I installed the adapter without problem.
But I is not possible to add a device...
The save button is gray and inactive and there is no button for a second device.

![radar adapter](https://user-images.githubusercontent.com/35842391/46907465-016c4080-cf13-11e8-9fa5-05aa942e7068.png)

**Comment by frankjoke** [comment]
Hi Speedymk1!
You need to scroll down until you see an empty line with a '+' as the first item, then click on the '+' to add another empty line.
