### ISSUE TITLE
node 10 support by using forked noble ...

### ISSUE THREAD

**Issue by Apollon77** [frankjoke/ioBroker.radar#27]
Hey,

we forced some tasks and there is now a forked noble that also offers nodejs 10 support.

Please upgrade to this fork: see e.g. https://github.com/AlCalzone/ioBroker.ble/commit/6851414e0aecff450d43ae7ba34a0146419d6f7a

Then also #20 should work :-)

**Comment by frankjoke** [comment]
Let's see, hope it works!
