### ISSUE TITLE
All devices are listed in AllUnknownIPs

### ISSUE THREAD

**Issue by tmsd2001** [frankjoke/iobroker.radar#3]
Hello,

All devices are listed in AllUnknownIPs.
Even though listed in radar config.
Tested at Rasbian and Ubuntu 16.04.
Radar Version 0.7.3

regards
ThomasD

**Comment by frankjoke** [comment]
Thanks to bring this up. It seems that some devices are even there multiple times. Need to check if the returned data of some modules changed and I need to update most probably the noble and arp-scan part.

**Comment by frankjoke** [comment]
I checked in latest version and could not find issue anymore
