### ISSUE TITLE
Scan Delay Zeit verändern

### ISSUE THREAD

**Issue by krettek** [frankjoke/ioBroker.radar#30]
Hi,

mir ist bekannt, dass es bereits Anfragen dazu gegeben hab und die Auskunft dazu, dass der Abstand zwischen zwei Scans nicht weiter verringert werden kann, da ein scan abhängig vom Rechner bereits eine bestimmte Zeit benötigt und dies nicht unterschritten werden kann.
Ich möchte jedoch den Radar Adapter zusammen mit G-Tag Bluetooth Beacons für die Anwesenheitskontrolle und zur Deaktivierung eines Alarmzustandes benutzen. Dafür ist die kürzeste Aktualisierungszeit von 15 Sekunden jedoch zu lang.
Da ich lediglich den Bluetooth Scan verwende, wäre die Frage, ob es nicht doch möglich ist, den Delay weiter runterzuschrauben?
Ich hab bereits selbst in der radar.js im Abschnitt zum Delay die 15 gegen eine 5 getauscht und in den Einstellungen auch. Allerdings wird immer noch erst in 15 Sekunden aktualisiert.
Lässt sich da dennoch was machen oder ist das gänzlich ausgeschlossen?

**Comment by frankjoke** [comment]
Ich arbeite gerade an einer Version welche dies vielleicht ermöglicht, es wird aber noch einige Wochen dauern um genaues sagen zu können da ich viel testen muss.

p.s.: 15s sind schon sehr kurz, weniger als 5-10 werden es nie werden da die Schnittstellen auch nicht schneller reagieren. z.B. dauert daas einloggen in ein Netz immer ~ 5 Sekunden!

**Comment by krettek** [comment]
Ok.
Vielen Dank für die schnelle Aufklärung.
Dann warte ich mal geduldig ab.
