### ISSUE TITLE
Netzwerk nur IP

### ISSUE THREAD

**Issue by SchafferApp** [frankjoke/iobroker.radar#34]
Es werden über Netzwerk nur die IP Adressen erkannt, jedoch nicht MAC Adressen.

**Comment by SchafferApp** [comment]
arp-scan ist installiert

**Comment by frankjoke** [comment]
LJ, hast probiert ob händisches arp-scan `sudo arp-scan -lgq` die Macs anzeigt?
Macs werden gefunden wenn sie eine gültige IP-Adresse im selben Netz haben (das erste mit IPv4 im altenb radar). 
Beim neuen Radar2-Adapter (kannst per git testen) werden auf allen IPv4-Netzwerken die vom Rechner angeschlossen sind arp-scan ausgeführt.

Leider kann arp-scan nichts finden wenn das Gegenüber nur mit IPv6 verbunden ist.
Der radar2 kann auch IPv6-adressen pingen. Besser ist es jedoch nicht die IP-Adresse anzugeben sondern den Namen, dann sucht radar2 nach allen IPv4 oder IPv6-Adressen die der router diesem Namen zugewiesen hat.

schau mal auf https://github.com/frankjoke/ioBroker.radar2
