### ISSUE TITLE
no arp-scan is available & Segmentation fault 

### ISSUE THREAD

**Issue by andreasploetz** [frankjoke/iobroker.radar#35]
Radar 1.2.1 in ioBroker unter Debian 9.7-1 auf Proxmox LCX-Container

Die im Topic genannten Fehler treten auf, arp-scan ist installiert und kann in der Konsole auch erfolgreich ausgeführt werden. Installation von ioBroker ist clean erfolgt und anschließend nur Radar mit den dazugehörigen Elementen (arp-scan, etc.) installiert.

`
host.ioBroker | 2019-03-06 16:23:06.673 | error | instance system.adapter.radar.0 terminated with code null ()
-- | -- | -- | --
host.ioBroker | 2019-03-06 16:23:06.673 | warn | instance system.adapter.radar.0 terminated due to SIGABRT
host.ioBroker | 2019-03-06 16:23:06.673 | error | Caught by controller[0]: 0: ../deps/uv/src/unix/poll.c:123: uv_poll_start: Assertion `!(((handle)->flags & (UV_HANDLE_CLOSING \| UV_HANDLE_CLOSED)) != 0)' failed.
radar.0 | 2019-03-06 16:23:05.786 | info | Init item Andreas with { name: 'Andreas', ip: '192.168.1.207', macs: '08:C5:E1:F7:F0:E8', bluetooth: '10:8E:E0:1C:9B:55', id: 'Andreas', hasMAC: [ '08:C5:E1:F7:F0:E8' ], hasBT: true, pri
radar.0 | 2019-03-06 16:23:05.785 | warn | MAC addresses '08:C5:E1:F7:F0:E8' will not be scanned because no arp-scan is available!
radar.0 | 2019-03-06 16:23:05.759 | info | BT Bin Dir = '/opt/iobroker/node_modules/iobroker.radar\bin\bluetoothview\'
radar.0 | 2019-03-06 16:23:05.759 | info | radar set to scan every 60 sec and printers every 500 scans.
radar.0 | 2019-03-06 16:23:05.759 | info | found '@abandonware/noble'
radar.0 | 2019-03-06 16:23:05.758 | info | starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.radar, node: v8.15.1
`

Vielleicht weiß einer weiter - da alle anderen Komponenten funktionieren und ich diesen Fehler schon auf mehreren Installationen hatte.

**Comment by frankjoke** [comment]
At first this seem to be one installation problem which others mentioned as well on new ioBroker installs which do not run as root.

Some users mentioned that they had wrong version of python installed when doing installation of the adapter which cases the npm to use wrong compile statements.

In any case, I would switch to radar2 (and make sure you run the installation script mentioned in readme BEFORE installing it!
