### ISSUE TITLE
Memory leak?!

### ISSUE THREAD

**Issue by AlGu1** [frankjoke/iobroker.radar#38]
Hi,
my radar instance used currently 13 GB of my RAM (see screenshot). I think it is not normal.
Who can i help to fix this?

Thanks
![Radar-Adapter](https://user-images.githubusercontent.com/18306111/54826364-faaadc00-4caf-11e9-826e-b3d6bf611e71.png)

AlGu

**Comment by frankjoke** [comment]
Hi AlGu,
This cannot be real. You are the first with such a claim.

Regardless, I would switch to new radar which is radar2. All my test instances and also my production instance show between 30 and 60mb of memory usage.

**Comment by frankjoke** [comment]
I close the issue because I support only changes to radar2.
