### ISSUE TITLE
root Rechte erfoderlich auf OrangePI

### ISSUE THREAD

**Issue by lubeda** [frankjoke/iobroker.radar#5]
Hallo,
mit dem Image aus dem Forum für den OrangePi Plus 2e sind scheinbar root Rechte für den Adapter erfoderlich. fping und arp-scan sind installiert laufen aber in der console nur mit sudo.

Log:
![grafik](https://cloud.githubusercontent.com/assets/17859549/26369058/ceab2530-3ff3-11e7-99aa-de6a41454583.png)

**Comment by lubeda** [comment]
War kein Problem vom Adapter. Man muss den User iobroker bei diesem Image in dir Gruppe Root aufnehmen und die jeweiligen Programe mit setuid Modus starten
`sudo chmod ug+s /usr/bin/arp-scan`

**Comment by frankjoke** [comment]
It is strange because my ioBroker runs on Raspi automatically as superuser, therefore also the adapters which get launched from it are superusers.. This is default when I use the ioBroker setup as described on home page.
