### ISSUE TITLE
Bluetooth devices are detected as "present" but are not there 

### ISSUE THREAD

**Issue by Apollon77** [frankjoke/iobroker.radar#6]
See http://forum.iobroker.net/viewtopic.php?p=76130#p76130

It seems that it sometimes happens that bluetooth devices are detected as "present", but the physical device is not even there. Several users noted that.

Is there anything that can be optimized? Maybe only detect bluetooth as "present" if at least two times there or such?

Ingo

**Comment by frankjoke** [comment]
The radar adapter just using standard tools from operation system to scan the devices.
On Unix it uses noble and l2ping to identify devices.

I have seen systems caching the information and providing a wrong answer.

You can use l2ping from command line to test if it creates the wrong status. Noble can only be used in javascript and you could test with the javascript BT script on the ioBroker web to check if Noble is generating the wrong data.

In any case, I can only use the info I get from the system and if any of the tools like Noble or l2ping lists the device as available I flag it as such as well.

**Comment by Apollon77** [comment]
is there logging available (e.g. as debig in the adapter?) to see whats exactly causing this ... so is it noble or l2ping or such and maybe also "why"?! Any chance to debug this?

**Comment by frankjoke** [comment]
You can set debug output and see some more info, one line is there which tells you how many noble found from the list and how many not in the list.
But it does not present all data received from the drivers.

**Comment by Apollon77** [comment]
Ok, then it's becoming interesting ... Attached Log from a timepoint today where my device because active in adapter, but was not there. Logging says "0 found", but then it is set to true ...

Affected device here is "Ingos-IPhone". You can find all data in log.
[radar-log.txt](https://github.com/frankjoke/iobroker.radar/files/1161962/radar-log.txt)

Any idea!?

**Comment by frankjoke** [comment]
Ok, so it seems that noble does not find it and it might be l2ping which lists it.

can you check on command line: sudo l2ping -c1 'BTMAC of phone'

If you get 'Host is down' then it's not visible, but if you get 1 sent, 1 received, 0% loss then it's still registered in the BT strack.

Do you run ioBroker under Windows? If yes, then Bluetoothview might be the tool listing it.
You can start it directly, go to \\???\ioBroker\node_modules\iobroker.radar\bin\bluetoothview
and start the exe in there.

One of the two (l2ping on linux or bluetoothview on windows set the flag because all flags are set to false on beginning of each scan!

**Comment by Apollon77** [comment]
I run under Linux (Ubuntu).
When I run l2ping with the provided parameters and my BT Mac then I get "Can't connect: Host down" now.
But also "it's still registered" can not be the case because:

I left my house this morning at 8:00 and btHere was correctly set to false.
Then at 11:46 as shown in logs it was set to "btHere=true" ONCE (so 11:45 was "false" and 11:47 was "false" too) and I was in company the whole time.

I have these cases 1-3 times a day in the timeframes where I'm not here.

And because of this it's very hard to  test it because it's only somewhen for one time ...

Would it be possible for you to add logging for l2ping to see what it returns in those cases ( I'm not that fit in "promisified code" to do it by my own without needing a long time).

**Comment by frankjoke** [comment]
Hallo Appolon77!
Hab mal genauer nachgeschaut und gefunden dass l2ping die Ursache scheint. 
Es wird direct neben einem anderen (linux)-Test ausgeführt: hcitool name BTMAC

Leider scheint es zu passieren dass l2ping in einen anderen Fehler läuft wenn BT-ressources noch von hcitools verwendet werden und es leider keinen 'host down' zurückgibt. Da du etwas anderes als einen Raspi zu verwenden scheinst tritt dieser Fehler anscheinend leider mit unterschiedlicher Wahrscheinlichkeit auf da andere Treiber/Geschwindigkeiten im Spiel sind.

Hab nun dafür gesorgt dass l2ping nur 100ms nach hcitools läuft, und auch nur dann falls hcitools nichts gefunden hat (deshalb verwende ich beide) und auch bei anderen Fehlern keine falsche Meldung gibt.

Habe auf Git den Adapter upgedated und auch viel mehr Debug-Meldungen eingebaut damit man erkennen kann welcher BT-Test zuschlägt.

**Comment by Apollon77** [comment]
Version von Github ist installiert und teste :-)

Ja, du hast recht auf einem Cubietruck hatte ich den Effekt nicht, auf dem NUC hab ich den Effekt.

**Comment by Apollon77** [comment]
In den neuen Logs:

2017-07-21 05:02:35.074  - debug: radar.0 Error: Command failed: l2ping -c1 54:4E:90:4F:41:64
2017-07-21 05:02:40.228  - debug: radar.0 l2ping for Ingos-IPhone err: "Error: Command failed: l2ping -c1 54:4E:90:4F:41:64
Aber auch zu den Zeiten wo ich daheim war und er BT erkannt hatte.

Ab und an finde ich aber auch: 

2017-07-21 08:49:09.058  - debug: radar.0 l2ping found Ingos-IPhone with "Ping: 54:4E:90:4F:41:64 from 5C:E0:C5:BB:A1:E7 (data size 44) ...
2017-07-21 08:49:43.160  - debug: radar.0 Error: Command failed: l2ping -c1 54:4E:90:4F:41:64
2017-07-21 08:49:48.321  - debug: radar.0 l2ping for Ingos-IPhone err: "Error: Command failed: l2ping -c1 54:4E:90:4F:41:64

Ist da Logging falsch/komisch?

**Comment by Apollon77** [comment]
PS: Heute noch keine falsche Bluetooth-Anwesenheit bisher

**Comment by frankjoke** [comment]
Appollon77, Error Command failed ist der Fehler der vorher das false-false true erzeugt hat da er leider nichts am Stdout zurückgegeben hat  und er deshalb nicht erkannt wurde.

Leider tritt der Fehler ab und zu auf, kann sein dass sich da neben hci noch andere BT-Funktionen überkreuzen.

l2ping found 'xxx' bedeutet dass l2ping Daten vom xxx zurückbekommen hat und es als 'bthere' eingestuft wird.

Wenn hcitools allerdings 'xxx' schon findet dann wird l2ping gar nicht mehr aufgerufen.

p.s.: Habe das eigenartige Problem dass sich mein Galaxy s7e fast immer auf hci gemeldet hat aber meiner Frau ihr Galaxy s7 meist erst mit l2ping obwohl sie gleiche Android-Version haben! 

Werde den bug jetzt schließen da ich im Program,m selbst nicht mehr machen kann und nur noch von der verwendeten HW und den Abstänen zu den Geräten abhängig bin.

**Comment by Apollon77** [comment]
Passt auch. Heute ganzer Tag keine fehler und gestern auch. Und ein zweiter Forum-User ebenso.
Kannst es denke ich auf npm publishen
