### ISSUE TITLE
Is UWZ Weather Warnings really "Radar adapter for IP and Bluetooth"?

### ISSUE THREAD

**Issue by Apollon77** [frankjoke/ioBroker.radar#8]
Hi,

"Weather" is an own adapter category and the question is if this new feature makes really sense? No User awaits this feature ... :-(
I would prefer to have a separate UWZ Warnings adapter.

Please think about it

Ingo

**Comment by frankjoke** [comment]
Hi Ingo!
I know but I did not want to write another adapter, just fill in 2 procedures on the existing one.

I wanted already to discuss if we can 'standardise'  an adapter interface for adapter plugins. 
I would like to be able to add plugins to adapters not to have so many separate adapters running (each of them requires 30MB on a raspi) but to 'plug in' like the proxy adapter.

I believe we would need an official plug in pattern to be integrated into adapter.js.

It would then be much easier to write and config separate adapters not using the full adapter overhead for each of them, just the 3-4 standard functions like ready, unload, message, interface and potential additional libraries from the host adapter to be re-used.

This could lead for example into a Javascript adapter where you can plug in blocky or (in my case) my stateMachine script. 

It could also be used to host a webinfo-host Adapter (I wanted to write one already) where you plug in the different sources, like the Weather, UWZ, Preise, Ink-fillings of printers or even things like my new BMW adapter.

**Comment by Apollon77** [comment]
Hi,

I partly understand your point, but for users and especially for the robustnes of the whole system these separated processes are very important and also part of the core concepts.

For this case a schedule adapter would be completely enough which is only started on schedule and so only needs that memory at some small timepoints. This should not be a problem and would not mix functionalities.

If you want to start such a discussion I would say: start a trello card to have it placed and also discussed there.

**Comment by frankjoke** [comment]
Ingo, habe ein Problem mit den Tests bei meinem broadlink2-Adapter!

Travis meldet:
 1 passing (40s)
  1 failing
  1) Test broadlink2 adapter Test broadlink2 adapter: Check if adapter started:
      Uncaught AssertionError: expected 'Cannot check connection' to not equal 'Cannot check connection'
      + expected - actual
      
      at test/testAdapter.js:108:35
      at checkConnectionOfAdapter (test/testAdapter.js:18:17)
      at null._onTimeout (test/testAdapter.js:28:17)
npm ERR! Test failed.  See above for more details.

Was kann ich dagegen tun?

**Comment by Apollon77** [comment]
Naja, schau mal in die Ausgaben über den "try #x" zeilen rein:

Cannot find: C:\projects\iobroker.broadlink2\tmp/node_modules/iobroker.broadlink2/broarlink2.js

Ich tippe Du hast in der package.json den "main" script name falsch drin :-)

**Comment by frankjoke** [comment]
Super Ingo! 
Das war's, was so ein 'r' statt 'b' ausrichten kann :(

Danke
Frank

**Comment by Apollon77** [comment]
Und Wald und Bäume und so :-)) Wenn es schon beim ersten Testingschritt hängt dann lohnt sich immer nach Fehlern zu schauen nachdem "start Adapter "bzw auch "start JS-Controller"

**Comment by frankjoke** [comment]
Tests are OK for Nodejs 4,6 and 8. required some changes in json files after adapter rename.
