### ISSUE TITLE
Add BLE Discovery?!

### ISSUE THREAD

**Issue by Apollon77** [frankjoke/ioBroker.radar#9]
Hey,

would it be possible to also add BLE Device discovery and maybe find/check/Store RSSI?!
Therefor it would be needed to set some Service UUIDs or such instead of the BT Address

**Comment by frankjoke** [comment]
Hi Ingo!
Actually the noble-scan includes the RSSI data but I did not store it. I will check on next update if I can include it into the report. Currently you can see it only in listing of 'AllUnknownBTs' . 
I was thinking also to extend the 'AllUnknown's' with better info output as well (added already some vendor data check).

**Comment by Apollon77** [comment]
Unknowns are only "real BT devices". Bluetooth LE is working differently. When I understand it correctly (need to test) you need to provide the BTLE Service UUIDs in the first array on startScanning call: https://github.com/sandeepmistry/noble#start-scanning. you have the one empty currently.

**Comment by frankjoke** [comment]
Ingo, I use this discovery just allowing all services.
